<template><div><h1 id="introduction" tabindex="-1"><a class="header-anchor" href="#introduction"><span>Introduction</span></a></h1>
<div class="hint-container warning">
<p class="hint-container-title">Warning</p>
<p>New versions (V3 and later) are not compatible with V2, so we recommend that you full reinstall Alist if you are upgrading from V2.</p>
</div>
<p><a href="https://github.com/Xhofe/alist/releases/latest" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/release/Xhofe/alist?style=flat-square" alt="" loading="lazy"></a><br>
<a href="https://github.com/Xhofe/alist/discussions" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/discussions/Xhofe/alist?color=%23ED8936&amp;style=flat-square" alt="GitHub Discussions" loading="lazy"></a><br>
<a href="https://github.com/Xhofe/alist/actions?query=workflow%3ABuild" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/actions/workflow/status/Xhofe/alist/build.yml?style=flat-square" alt="" loading="lazy"></a><br>
<a href="https://github.com/Xhofe/alist/releases" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/downloads/Xhofe/alist/total?style=flat-square&amp;color=%239F7AEA" alt="" loading="lazy"></a><br>
<a href="https://pay.xhofe.top" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/badge/%24-donate-ff69b4.svg?style=flat-square" alt="" loading="lazy"></a></p>
<h3 id="what-s-this" tabindex="-1"><a class="header-anchor" href="#what-s-this"><span>What's this</span></a></h3>
<p>A file list program that supports multiple storage, and supports web browsing and webdav, powered by gin and Solidjs.</p>
<h3 id="support-storage" tabindex="-1"><a class="header-anchor" href="#support-storage"><span>Support storage</span></a></h3>
<ul class="task-list-container">
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-0" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-0"> <RouteLink to="/guide/drivers/local.html">Local storage</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-1" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-1"> <RouteLink to="/guide/drivers/Crypt.html">Crypt</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-2" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-2"> <RouteLink to="/guide/drivers/aliyundrive_open.html">Aliyundrive Open</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-3" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-3"> <a href="https://www.alipan.com/" target="_blank" rel="noopener noreferrer">aliyundrive</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-4" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-4"> <RouteLink to="/guide/drivers/onedrive.html">OneDrive</RouteLink> /<RouteLink to="/guide/drivers/onedrive_app.html">APP</RouteLink>/ Sharepoint (<a href="https://www.office.com/" target="_blank" rel="noopener noreferrer">global</a>, <a href="https://portal.partner.microsoftonline.cn" target="_blank" rel="noopener noreferrer">cn</a>,de,us）</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-5" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-5"> <a href="https://drive.google.com/" target="_blank" rel="noopener noreferrer">GoogleDrive</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-6" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-6"> <a href="https://www.123pan.com/" target="_blank" rel="noopener noreferrer">123pan/Share/Link</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-7" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-7"> <a href="https://github.com/Xhofe/alist" target="_blank" rel="noopener noreferrer">Alist</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-8" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-8"> FTP</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-9" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-9"> SFTP</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-10" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-10"> <a href="https://www.mypikpak.com/" target="_blank" rel="noopener noreferrer">PikPak / share</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-11" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-11"> <RouteLink to="/guide/drivers/s3.html">S3</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-12" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-12"> <RouteLink to="/guide/drivers/s3.html#add-object-storage-examples-and-official-documents">Doge</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-13" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-13"> <a href="https://www.upyun.com/products/file-storage" target="_blank" rel="noopener noreferrer">UPYUN Storage Service</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-14" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-14"> WebDAV</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-15" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-15"> Teambition（<a href="https://www.teambition.com/" target="_blank" rel="noopener noreferrer">China</a>，<a href="https://us.teambition.com/" target="_blank" rel="noopener noreferrer">International</a>）</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-16" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-16"> <a href="https://www.mediatrack.cn/" target="_blank" rel="noopener noreferrer">mediatrack</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-17" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-17"> <a href="https://cloud.189.cn" target="_blank" rel="noopener noreferrer">189cloud</a> (Personal, Family)</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-18" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-18"> <a href="https://yun.139.com/" target="_blank" rel="noopener noreferrer">139yun</a> (Personal, Family)</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-19" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-19"> <a href="https://pan.wo.cn" target="_blank" rel="noopener noreferrer">Wopan</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-20" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-20"> <a href="https://mopan.sc.189.cn/mopan/#/downloadPc" target="_blank" rel="noopener noreferrer">MoPan</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-21" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-21"> <a href="https://disk.yandex.com/" target="_blank" rel="noopener noreferrer">YandexDisk</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-22" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-22"> <a href="https://pan.baidu.com/" target="_blank" rel="noopener noreferrer">BaiduNetdisk</a> / <RouteLink to="/guide/drivers/baidu_share.html">share</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-23" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-23"> <a href="https://pan.quark.cn/" target="_blank" rel="noopener noreferrer">Quark/TV</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-24" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-24"> <RouteLink to="/guide/drivers/thunder.html">Thunder / X Browser</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-25" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-25"> <a href="https://www.lanzou.com/" target="_blank" rel="noopener noreferrer">Lanzou</a>、<a href="https://www.ilanzou.com" target="_blank" rel="noopener noreferrer">NewLanzou</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-26" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-26"> <a href="https://feijipan.com/" target="_blank" rel="noopener noreferrer">Feiji Cloud</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-27" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-27"> <a href="https://www.alipan.com/" target="_blank" rel="noopener noreferrer">Aliyundrive share</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-28" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-28"> <a href="https://photos.google.com/" target="_blank" rel="noopener noreferrer">Google photo</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-29" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-29"> <a href="https://mega.nz" target="_blank" rel="noopener noreferrer">Mega.nz</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-30" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-30"> <a href="https://photo.baidu.com/" target="_blank" rel="noopener noreferrer">Baidu photo</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-31" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-31"> <a href="https://www.terabox.com/" target="_blank" rel="noopener noreferrer">TeraBox</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-32" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-32"> <RouteLink to="/guide/drivers/Alist%20V2%20V3.html">AList v2/v3</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-33" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-33"> SMB</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-34" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-34"> <RouteLink to="/guide/advanced/alias.html">alias</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-35" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-35"> <a href="https://115.com/" target="_blank" rel="noopener noreferrer">115</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-36" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-36"> <a href="https://www.seafile.com/" target="_blank" rel="noopener noreferrer">Seafile</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-37" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-37"> Cloudreve</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-38" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-38"> <a href="https://trainbit.com/" target="_blank" rel="noopener noreferrer">Trainbit</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-39" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-39"> <RouteLink to="/guide/drivers/UrlTree.html">UrlTree</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-40" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-40"> IPFS</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-41" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-41"> <a href="https://drive.uc.cn/" target="_blank" rel="noopener noreferrer">UC Clouddrive/TV</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-42" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-42"> <a href="https://www.dropbox.com" target="_blank" rel="noopener noreferrer">Dropbox</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-43" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-43"> <a href="https://www.weiyun.com/" target="_blank" rel="noopener noreferrer">Tencent weiyun</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-44" disabled="disabled"><label class="task-list-item-label" for="task-item-44"> <a href="https://app.v.tencent.com/" target="_blank" rel="noopener noreferrer">vtencent</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-45" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-45"> <RouteLink to="/guide/drivers/chaoxing.html">ChaoxingGroupCloud</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-46" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-46"> <a href="https://quqi.com" target="_blank" rel="noopener noreferrer">Quqi Cloud</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-47" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-47"> <RouteLink to="/guide/drivers/163music.html">163 Music Drive</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-48" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-48"> <RouteLink to="/guide/drivers/halalcloud.html">halalcloud</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-49" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-49"> <a href="https://pc.lenovo.com.cn" target="_blank" rel="noopener noreferrer">LenovoNasShare</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-50" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-50"> <RouteLink to="/guide/drivers/github.html">GitHub API</RouteLink> / <RouteLink to="/guide/drivers/github_releases.html">GitHub Release</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-51" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-51"> <a href="https://misskey-hub.net/cn/docs/for-users/features/drive/" target="_blank" rel="noopener noreferrer">Misskey</a></label></li>
</ul>
<h3 id="discussion" tabindex="-1"><a class="header-anchor" href="#discussion"><span>Discussion</span></a></h3>
<p>Please go to our <a href="https://github.com/Xhofe/alist/discussions" target="_blank" rel="noopener noreferrer">discussion forum</a> for general questions, <strong>issues are for bug reports and feature request only.</strong></p>
<h3 id="demo" tabindex="-1"><a class="header-anchor" href="#demo"><span>Demo</span></a></h3>
<ul>
<li><a href="https://al.nn.ci" target="_blank" rel="noopener noreferrer">https://al.nn.ci</a></li>
</ul>
<!-- ### Special sponsors

- [VidHub](https://apps.apple.com/app/apple-store/id1659622164?pt=118612019&ct=alist&mt=8) - An elegant cloud video player within the Apple ecosystem. Support for iPhone, iPad, Mac, and Apple TV.
- [亚洲云](https://www.asiayun.com/aff/QQCOOQKZ) - 高防服务器|服务器租用|福州高防|广东电信|香港服务器|美国服务器|海外服务器 - 国内靠谱的企业级云计算服务提供商 (sponsored Chinese API server)
- [找资源](http://zhaoziyuan2.cc/) - 阿里云盘资源搜索引擎 -->
<h3 id="license" tabindex="-1"><a class="header-anchor" href="#license"><span>License</span></a></h3>
<p>The <code v-pre>AList</code> is open-source software licensed under the AGPL-3.0 license.</p>
</div></template>


