<template><div><h1 id="手动安装" tabindex="-1"><a class="header-anchor" href="#手动安装"><span>手动安装</span></a></h1>
<h2 id="获取-alist" tabindex="-1"><a class="header-anchor" href="#获取-alist"><span><strong>获取 AList</strong></span></a></h2>
<p>打开 <a href="https://github.com/Xhofe/alist/releases" target="_blank" rel="noopener noreferrer">AList Release</a> 下载待部署系统对应的文件。最新版的前端已经和后端打包好了，不用再下载前端文件了。</p>
<p>xxxx 指的是不同系统/架构对应的名称，一般 Linux-x86/64 为 alist-linux-amd64</p>
<p>手动安装如果有如下提示：是因为<RouteLink to="/zh/faq/why.html#lib64-libc-so-6-version-glibc-2-28-not-found-required-by-alist-%E6%88%96%E8%80%85-accept-function-not-implemented">你的 GLIBC 版本太低</RouteLink>，建议下载 musl 版本</p>
<div class="language-txt line-numbers-mode" data-highlighter="shiki" data-ext="txt" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-txt"><span class="line"><span>lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)  </span></span>
<span class="line"><span>#或者</span></span>
<span class="line"><span>accept: function not implemented</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>当你看到 <code v-pre>start server@0.0.0.0:5244</code> 的输出，之后没有报错，说明操作成功。 第一次运行时会输出初始密码。程序默认监听 5244 端口。 现在打开 <code v-pre>http://ip:5244</code> 可以看到登录页面，WebDAV 请参阅 <RouteLink to="/zh/guide/webdav.html">WebDav</RouteLink>。</p>
<br/>
<h2 id="手动运行" tabindex="-1"><a class="header-anchor" href="#手动运行"><span><strong>手动运行</strong></span></a></h2>
<p>v3.25.0以上版本将密码改成加密方式存储的hash值，无法直接反算出密码，如果忘记了密码只能通过重新 <strong><code v-pre>随机生成</code></strong> 或者 <strong><code v-pre>手动设置</code></strong></p>
<Tabs :data='[{"id":"Linux"},{"id":"macOS"},{"id":"Windows"},{"id":"win(scoop)"}]' tab-id="os">
<template #title0="{ value, isActive }">Linux</template>
<template #title1="{ value, isActive }">macOS</template>
<template #title2="{ value, isActive }">Windows</template>
<template #title3="{ value, isActive }">win(scoop)</template>
<template #tab0="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 解压下载的文件，得到可执行文件：</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">tar</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -zxvf</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist-xxxx.tar.gz</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 授予程序执行权限：</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">chmod</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> +x</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 运行程序</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 获得管理员信息 以下两个不同版本，新版本也有随机生成和手动设置</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 低于v3.25.0版本</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 高于v3.25.0版本</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 随机生成一个密码</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 手动设置一个密码 `NEW_PASSWORD`是指你需要设置的密码</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 解压下载的文件，得到可执行文件：</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">tar</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -zxvf</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist-xxxx.tar.gz</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 授予程序执行权限：</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">chmod</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> +x</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 运行程序</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 获得管理员信息 以下两个不同版本，新版本也有随机生成和手动设置</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 低于v3.25.0版本</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">#高于v3.25.0版本</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 随机生成一个密码</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 手动设置一个密码 `NEW_PASSWORD`是指你需要设置的密码</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab2="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 解压下载的文件，得到可执行文件：</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">unzip</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist-xxxx.zip</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 运行程序</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 获得管理员信息 以下两个不同版本，新版本也有随机生成和手动设置</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 低于v3.25.0版本</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 高于v3.25.0版本</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 随机生成一个密码</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 手动设置一个密码 `NEW_PASSWORD`是指你需要设置的密码</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab3="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 安装</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">scoop</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 运行</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</Tabs>
<br/>
<h2 id="守护进程" tabindex="-1"><a class="header-anchor" href="#守护进程"><span><strong>守护进程</strong></span></a></h2>
<Tabs :data='[{"id":"Linux"},{"id":"macOS"},{"id":"Windows"}]' tab-id="os">
<template #title0="{ value, isActive }">Linux</template>
<template #title1="{ value, isActive }">macOS</template>
<template #title2="{ value, isActive }">Windows</template>
<template #tab0="{ value, isActive }">
<p>使用任意方式编辑 <code v-pre>/usr/lib/systemd/system/alist.service</code> 并添加如下内容，其中 path_alist 为 AList 所在的路径</p>
<div class="language-ini line-numbers-mode" data-highlighter="shiki" data-ext="ini" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-ini"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">[Unit]</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">Description</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">alist</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">After</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">network.target</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#98C379"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">[Service]</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">Type</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">simple</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">WorkingDirectory</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">path_alist</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">ExecStart</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">path_alist/alist server</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">Restart</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">on-failure</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#98C379"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">[Install]</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">WantedBy</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">multi-user.target</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后，执行 <code v-pre>systemctl daemon-reload</code> 重载配置，现在你可以使用这些命令来管理程序：</p>
<ul>
<li>启动: <code v-pre>systemctl start alist</code></li>
<li>关闭: <code v-pre>systemctl stop alist</code></li>
<li>配置开机自启: <code v-pre>systemctl enable alist</code></li>
<li>取消开机自启: <code v-pre>systemctl disable alist</code></li>
<li>状态: <code v-pre>systemctl status alist</code></li>
<li>重启: <code v-pre>systemctl restart alist</code></li>
</ul>
<p>守护进程不配置? <a href="https://www.bilibili.com/video/BV1rF41197Qv?t=187.0" target="_blank" rel="noopener noreferrer"><strong>视频教程</strong></a></p>
</template>
<template #tab1="{ value, isActive }">
<p>使用任意方式编辑 <code v-pre>~/Library/LaunchAgents/ci.nn.alist.plist</code> 并添加如下内容，修改 <code v-pre>path_alist</code> 为 AList 所在的路径，<code v-pre>path/to/working/dir</code> 为 AList的工作路径</p>
<div class="language-xml line-numbers-mode" data-highlighter="shiki" data-ext="xml" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-xml"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;?</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">xml</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> version</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"1.0"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> encoding</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"UTF-8"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">?></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;!</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">DOCTYPE</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B"> plist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">plist</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> version</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"1.0"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">dict</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>Label&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>ci.nn.alist&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>KeepAlive&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">true</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>ProcessType&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>Background&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>RunAtLoad&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">true</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>WorkingDirectory&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>path/to/working/dir&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>ProgramArguments&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">array</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>path_alist/alist&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">            &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>server&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">        &#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">array</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">    &#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">dict</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">plist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>然后，执行 <code v-pre>launchctl load ~/Library/LaunchAgents/ci.nn.alist.plist</code> 加载配置，现在你可以使用这些命令来管理程序：</p>
<ul>
<li>开启: <code v-pre>launchctl start ~/Library/LaunchAgents/ci.nn.alist.plist</code></li>
<li>关闭: <code v-pre>launchctl stop ~/Library/LaunchAgents/ci.nn.alist.plist</code></li>
<li>卸载配置: <code v-pre>launchctl unload ~/Library/LaunchAgents/ci.nn.alist.plist</code></li>
</ul>
</template>
<template #tab2="{ value, isActive }">
<h3 id="方法1" tabindex="-1"><a class="header-anchor" href="#方法1"><span><strong>方法1</strong></span></a></h3>
<ol>
<li>在 <a href="https://nssm.cc/download" target="_blank" rel="noopener noreferrer">https://nssm.cc/download</a> 下载最新版本的 <code v-pre>nssm</code>；</li>
<li>在解压后的文件夹内按住 Shift 并右击空白处，选择“在此处打开 Powershell 窗口”；</li>
<li>在弹出的窗口中输入 <code v-pre>.\nssm.exe install alist</code>；</li>
<li>Path 选择 alist.exe 的路径，如 <code v-pre>D:\alist\alist.exe</code>，Arguments 填 <code v-pre>server</code>；</li>
<li>Details 选项卡中可以自定义标题和描述，可以选择服务的自启动模式（自动|延迟启动|手动|禁用）；</li>
<li>在 I/O 选项卡为 Output (stdout) 和 Output (stderr) 各自指定一个日志文件的路径，如 <code v-pre>D:\alist\stdout.log</code>，文件本身（<code v-pre>stdout.log</code>）可以不存在，但是指定的目录（<code v-pre>D:\alist</code>）必须存在；</li>
<li>点击“Install Service”即可。</li>
</ol>
<p>此后可以直接在服务中启动 <code v-pre>alist</code>。</p>
<h3 id="方法2" tabindex="-1"><a class="header-anchor" href="#方法2"><span><strong>方法2</strong></span></a></h3>
<p>用  <strong><code v-pre>.VBS</code></strong> 脚本启动和停止，分别创建两个脚本 分别是  启动.vbs 和 停止.vbs</p>
<p>直接在和Alist启动程序同级文件夹里面双击启动即可，不用担心没有反应 直接去 浏览器访问即可</p>
<div class="hint-container info">
<p class="hint-container-title">两个启动脚本</p>
<p><strong>启动.vbs</strong></p>
<div class="code-block-with-title">
  <div class="code-block-title-bar" data-title="vbscript">
    <span>vbscript</span>
  </div>
  <div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Dim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ws</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ws</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> =</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Wscript.CreateObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"Wscript.Shell"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ws.run</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "alist.exe server",vbhide</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Wscript.quit</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div>
</div><p><strong>停止.vbs</strong></p>
<div class="code-block-with-title">
  <div class="code-block-title-bar" data-title="vbscript">
    <span>vbscript</span>
  </div>
  <div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Dim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ws</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ws</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> =</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Wscript.CreateObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"Wscript.Shell"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ws.run</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "taskkill /f /im alist.exe",0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Wscript.quit</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div>
</div><ol>
<li>
<p>脚本不会创建的可以自行下载：<a href="https://www.alipan.com/s/DHPMhRtKUzY/folder/63e0961eae317bd4d4d945cda69dbb00f9837fb7" target="_blank" rel="noopener noreferrer"><strong>脚本下载</strong></a></p>
</li>
<li>
<p>脚本不会使用的可以看看视频：<a href="https://www.bilibili.com/video/BV1DG411s7j5?t=266.2" target="_blank" rel="noopener noreferrer"><strong>参考视频</strong></a></p>
</li>
</ol>
<p>如何实现Windows开机自启，可以参考上面提到的脚本使用视频(第二个)</p>
</div>
</template>
</Tabs>
<div class="hint-container info">
<p class="hint-container-title">相关信息</p>
<p>对于所有平台，您可以使用以下命令来静默启动、停止和重新启动。 （v3.4.0 及更高版本）</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 携带`--force-bin-dir`参数启动服务</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> start</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 通过pid停止服务</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> stop</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 通过pid重启服务</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> restart</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div>
<br/>
<h2 id="如何更新" tabindex="-1"><a class="header-anchor" href="#如何更新"><span><strong>如何更新</strong></span></a></h2>
<p>下载新版Alist，把之前的替换了即可。</p>
<br/>
<ul>
<li>启动: <code v-pre>systemctl start alist</code></li>
<li>关闭: <code v-pre>systemctl stop alist</code></li>
<li>状态: <code v-pre>systemctl status alist</code></li>
<li>重启: <code v-pre>systemctl restart alist</code></li>
</ul>
<h2 id="获取密码" tabindex="-1"><a class="header-anchor" href="#获取密码"><span><strong>获取密码</strong></span></a></h2>
<p>需要进入脚本安装AList的目录文件夹內执行如下命令</p>
<h4 id="低于v3-25-0版本" tabindex="-1"><a class="header-anchor" href="#低于v3-25-0版本"><span>低于v3.25.0版本</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="高于v3-25-0版本" tabindex="-1"><a class="header-anchor" href="#高于v3-25-0版本"><span>高于v3.25.0版本</span></a></h4>
<p>3.25.0以上版本将密码改成加密方式存储的hash值，无法直接反算出密码，如果忘记了密码只能通过重新 <strong><code v-pre>随机生成</code></strong> 或者 <strong><code v-pre>手动设置</code></strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 随机生成一个密码</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># 手动设置一个密码,`NEW_PASSWORD`是指你需要设置的密码</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="一直在加载怎么办" tabindex="-1"><a class="header-anchor" href="#一直在加载怎么办"><span><strong>一直在加载怎么办?</strong></span></a></h2>
<p>挂载了一些网盘但是不能用了重启了一下AList，发现进不去 网页提示：<code v-pre>获取设置失败：请稍后，正在加载存储</code>怎么办？</p>
<ol>
<li>等待几分钟</li>
<li>通过使用命令将<code v-pre>失效的/无法启动的</code>存储停止运行</li>
</ol>
<Tabs :data='[{"id":"Linux"},{"id":"Windows"},{"id":"Mac"},{"id":"Docker"}]' tab-id="stop">
<template #title0="{ value, isActive }">Linux</template>
<template #title1="{ value, isActive }">Windows</template>
<template #title2="{ value, isActive }">Mac</template>
<template #title3="{ value, isActive }">Docker</template>
<template #tab0="{ value, isActive }">
<p>如果通过命令停止 <mark>必须先进入你AList所在的文件夹输入命令</mark></p>
<p>如果我们不知道是那个存储原因导致的，可以通过命令列出所有的存储</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# ./alist storage list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌─────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│─────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     S3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                /R2</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                             true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     UrlTree</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">           /233</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                            true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└─────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输入查询命令后我们会进入另一种模式无法输入，如果添加的存储过多可以通过键盘的 ↑ 和 ↓ 来往下翻，等找到后可以按<code v-pre>Ctrl+C</code>退出</p>
<p>例如我们是因为 <code v-pre>233</code> 这个存储停止的，我们就输入命令来停止，然后在 重启一下AList就可以了</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /233</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# ./alist storage disable /233</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> path</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [/233] have been disabled</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p></p>
</template>
<template #tab1="{ value, isActive }">
<p>如果通过命令停止 <mark>必须先进入你AList所在的文件夹输入命令</mark></p>
<p>如果我们不知道是那个存储原因导致的，可以通过命令列出所有的存储</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">C:\Users\admin\Desktop\alist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">onfig.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 13</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌──────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│──────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     AliyundriveOpen</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   /open</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                           true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 9</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     Local</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">             /code</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                           true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 10</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    AList</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> V3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">          /ceshi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                          true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└──────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输入查询命令后我们会进入另一种模式无法输入，如果添加的存储过多可以通过键盘的 ↑ 和 ↓ 来往下翻，等找到后可以按<code v-pre>Ctrl+C</code>退出</p>
<p>例如我们是因为 <code v-pre>open</code> 这个存储停止的，我们就输入命令来停止，然后在 重启一下AList就可以了</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /open</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">C:\Users\admin\Desktop\alist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /open</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">onfig.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> path</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [/open] have been disabled</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p></p>
</template>
<template #tab2="{ value, isActive }">
<p>如果通过命令停止 <mark>必须先进入你AList所在的文件夹输入命令</mark></p>
<p>由于暂时没有Mac设备，无法提供具体示例，但是命令都是一样的也可以参考 Linux 和 Windows</p>
<p>列出存储:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>停止存储:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /Path</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p></p>
</template>
<template #tab3="{ value, isActive }">
<p>这里的 <code v-pre>Docker</code> 目前只提供了使用文档命令安装的默认版本，<mark>如果你搭建多个Docker版本的AList你需要修改个别参数喔~</mark></p>
<p>如果我们不知道是那个存储原因导致的，可以通过命令列出所有的存储</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> exec</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -it</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# docker exec -it alist ./alist storage list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌─────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│─────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     PikPakShare</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /pikpak</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                         true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /utena_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /adelev_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 4</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /megan_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 5</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /patti_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└─────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输入查询命令后我们会进入另一种模式无法输入，如果添加的存储过多可以通过键盘的 ↑ 和 ↓ 来往下翻，等找到后可以按<code v-pre>Ctrl+C</code>退出</p>
</template>
</Tabs>
</div></template>


