<template><div><h1 id="从源码运行" tabindex="-1"><a class="header-anchor" href="#从源码运行"><span>从源码运行</span></a></h1>
<div class="hint-container caution">
<p class="hint-container-title">警告</p>
<p>此步骤仅适用于需要自行修改源代码的用户。 不明白的请跳过。</p>
</div>
<h2 id="环境准备" tabindex="-1"><a class="header-anchor" href="#环境准备"><span><strong>环境准备</strong></span></a></h2>
<p>首先，你需要一个有<code v-pre>git</code>，<code v-pre>nodejs</code>，<code v-pre>pnpm</code>，<code v-pre>golang&gt;=1.20</code>，<code v-pre>gcc</code>的环境</p>
<h2 id="构建前端" tabindex="-1"><a class="header-anchor" href="#构建前端"><span><strong>构建前端</strong></span></a></h2>
<p>使用 <code v-pre>git clone --recurse-submodules https://github.com/alist-org/alist-web.git</code> 克隆前端 ，执行 <code v-pre>pnpm install &amp;&amp; pnpm build</code> 得到 dist 目录下的目标文件</p>
<h2 id="构建后端" tabindex="-1"><a class="header-anchor" href="#构建后端"><span><strong>构建后端</strong></span></a></h2>
<p>克隆 <a href="https://github.com/alist-org/alist" target="_blank" rel="noopener noreferrer">https://github.com/alist-org/alist</a> ，将上一步的 <code v-pre>dist</code> 目录复制到项目下的 <code v-pre>public</code> 目录下，然后执行：</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">appName</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"alist"</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">builtAt</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">date</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> +'%F %T %z')"</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">goVersion</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">go</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> version</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sed</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 's/go version //'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gitAuthor</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> show</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'format:%aN &#x3C;%ae>'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> HEAD</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gitCommit</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> log</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --pretty=format:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"%h"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> describe</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --long</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --tags</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --dirty</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --always</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">webVersion</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">wget</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -qO-</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -t1</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -T2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://api.github.com/repos/alist-org/alist-web/releases/latest"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">grep</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "tag_name"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">head</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -n</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">awk</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -F</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ":"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '{print $2}'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sed</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 's/\"//g;s/,//g;s/ //g'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ldflags</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-w -s </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.BuiltAt=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$builtAt</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.GoVersion=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$goVersion</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.GitAuthor=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$gitAuthor</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.GitCommit=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$gitCommit</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.Version=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$version</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.WebVersion=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$webVersion</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">go</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> build</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -ldflags=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$ldflags</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> .</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><details class="hint-container details"><summary>你可能需要的编译教程视频</summary>
<p>Windows版本：<strong><a href="https://www.bilibili.com/video/BV1Xr4y1z723" target="_blank" rel="noopener noreferrer">https://www.bilibili.com/video/BV1Xr4y1z723</a></strong><br>
（虽然是V2版的，但是跟V3版本一样的..）</p>
<p>Linux版本：<strong><a href="https://www.bilibili.com/video/BV1GW4y1s742" target="_blank" rel="noopener noreferrer">https://www.bilibili.com/video/BV1GW4y1s742</a></strong></p>
<p>番外编译文档：<strong><a href="https://www.yuque.com/anwenya/alist/glqlhu" target="_blank" rel="noopener noreferrer">https://www.yuque.com/anwenya/alist/glqlhu</a></strong></p>
</details>
</div></template>


