<template><div><h1 id="mega-disk" tabindex="-1"><a class="header-anchor" href="#mega-disk"><span>MEGA Disk</span></a></h1>
<p>MEGA official website: <strong><a href="https://mega.nz/login" target="_blank" rel="noopener noreferrer">https://mega.nz/login</a></strong></p>
<h3 id="mail" tabindex="-1"><a class="header-anchor" href="#mail"><span><strong>Mail</strong></span></a></h3>
<p>MEGA login account</p>
<h3 id="password" tabindex="-1"><a class="header-anchor" href="#password"><span><strong>password</strong></span></a></h3>
<p>login password</p>
<h2 id="_2fa" tabindex="-1"><a class="header-anchor" href="#_2fa"><span><strong>2FA</strong></span></a></h2>
<p>Non -filling options,If you open 2FA, you need to fill in it,If you don’t use 2FA, you don’t need to fill in it</p>
<h3 id="two-fa-secret" tabindex="-1"><a class="header-anchor" href="#two-fa-secret"><span><strong>Two fa secret</strong></span></a></h3>
<p><strong><a href="https://mega.nz/fm/account/security/two-factor-authentication" target="_blank" rel="noopener noreferrer">https://mega.nz/fm/account/security/two-factor-authentication</a></strong></p>
<p>Click to enable <code v-pre>Enable two-factor authentication (2FA)</code> and then see a QR code, there is a string of letters below the QR code, This is <code v-pre>Two fa secret</code>, please record before scanning the code and do not lose it, Should the <code v-pre>Two-factor authentication (2FA) secret</code> be lost, you can unbinding and then retrieve a new 2FA QR code for setup.</p>
<p><img src="/img/drivers/mega/mega_2fa.png" alt="" loading="lazy"></p>
<h3 id="two-fa-code" tabindex="-1"><a class="header-anchor" href="#two-fa-code"><span><strong>Two fa code</strong></span></a></h3>
<p>To enable 2-factor authentication, you need to install a app that support 2FA (such as <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank" rel="noopener noreferrer">Google Authenticator</a>, <a href="https://support.microsoft.com/en-us/account-billing/download-and-install-the-microsoft-authenticator-app-351498fc-850a-45da-b7b6-27e523b8702a" target="_blank" rel="noopener noreferrer">Microsoft Authenticator</a>), on your phone.</p>
<p>Then login to ALIST manage and goto <code v-pre>Profile</code> page, click <code v-pre>Enable 2FA</code> button, scan the QR code with your 2FA app, and enter the code generated by your 2FA app.</p>
<p>Scan the QR appearing on the screen. At the same time, this QR code is also <a href="#two-fa-secret">two-fa-secret</a></p>
<p><img src="/img/drivers/mega/mega_2fa_code.png" alt="" loading="lazy"></p>
<br/>
<h2 id="fill-in-example" tabindex="-1"><a class="header-anchor" href="#fill-in-example"><span>Fill in example:</span></a></h2>
<p><img src="/img/drivers/mega/mega_add.png" alt="" loading="lazy"></p>
<br/>
<h3 id="the-default-download-method-used" tabindex="-1"><a class="header-anchor" href="#the-default-download-method-used"><span><strong>The default download method used</strong></span></a></h3>
<Mermaid id="mermaid-62" code="eJyNkL1uwjAURnee4gpWHBQooFpKK1WMnapWHaIMjn1dWzhxajskefuaNCA6VMKL/75z7HsJIbOgg0EKn0pzBcJ2tbFMQIVBWQHaQ+tRQDmAQMlaE55nZ0ga23HFXID3lxnE4cNgEHgKUhtDF2Uplz44e0S6kLvdtCadFkHRddMvuTXWxTspb3C2nnAp99v99mrYbDZ/DQ9N/4u15ZdjjQItMIUcivGUp+OEtZi2ubGcGWic7YeCUupthdww77NsqirLsie2zmOtDvC71U2FdZhs5+ABJVypyycfd2OgTPPDpW3jE/Dx9lqQhJmArmZBnzAh/9s1P0YFzJNkJVzMOr/itqpsnahQmUWHpWAn0tgYHOY3TOz1ncwPx9ee1g=="></Mermaid></div></template>


