<template><div><h2 id="get-alist" tabindex="-1"><a class="header-anchor" href="#get-alist"><span><strong>Get Alist</strong></span></a></h2>
<p>Open <a href="https://github.com/Xhofe/alist/releases" target="_blank" rel="noopener noreferrer">AList Release</a> to download the files corresponding to the system to be deployed. The latest version of the front-end has been packaged with the back-end, so there is no need to download the front-end files again.</p>
<p>The xxxx refers to the names corresponding to different systems/architectures, generally Linux-x86/64 is alist-linux-amd64.</p>
<p>If there is a prompt as follows：It is because <RouteLink to="/faq/why.html#lib64-libc-so-6-version-glibc-2-28-not-found-required-by-alist-or-accept-function-not-implemented">your GLIBC version is too low</RouteLink>, it is recommended to download the musl version</p>
<div class="language-txt line-numbers-mode" data-highlighter="shiki" data-ext="txt" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-txt"><span class="line"><span>lib64/libc.so.6: version `GLIBC_2.28' not found (required by ./alist)  </span></span>
<span class="line"><span># or</span></span>
<span class="line"><span>accept: function not implemented</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>When you see the output of <code v-pre>start server @ 0.0.0.0:5244</code> and no error is reported afterwards, it means that the operation is successful. The initial password will be output when running for the first time. The program listens to port 5244 by default. Now open <code v-pre>http://ip:5244</code> You can see the login page, please see <RouteLink to="/guide/webdav.html">WebDav</RouteLink> for webdav.</p>
<h2 id="running" tabindex="-1"><a class="header-anchor" href="#running"><span><strong>Running</strong></span></a></h2>
<p>Versions above v3.25.0 change the password to an encrypted hash value, and the password cannot be calculated directly. If the password is forgotten, it can only be re-<strong><code v-pre>randomly generated</code></strong> or <strong><code v-pre>manually set</code></strong></p>
<Tabs :data='[{"id":"linux"},{"id":"macOS"},{"id":"Windows"},{"id":"win(scoop)"}]' tab-id="os">
<template #title0="{ value, isActive }">linux</template>
<template #title1="{ value, isActive }">macOS</template>
<template #title2="{ value, isActive }">Windows</template>
<template #title3="{ value, isActive }">win(scoop)</template>
<template #tab0="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Unzip the downloaded file to get the executable file:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">tar</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -zxvf</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist-xxxx.tar.gz</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Grant program execution permissions:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">chmod</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> +x</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Run the program</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Obtain administrator information The following two different versions, the new version also has random generation and manual settings</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Versions lower than v3.25.0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># higher than v3.25.0 version</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Randomly generate a password</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Manually set a password `NEW_PASSWORD` refers to the password you need to set</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Unzip the downloaded file to get the executable file:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">tar</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -zxvf</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist-xxxx.tar.gz</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Grant program execution permissions:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">chmod</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> +x</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Run the program</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Obtain administrator information The following two different versions, the new version also has random generation and manual settings</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Versions lower than v3.25.0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># higher than v3.25.0 version</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Randomly generate a password</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Manually set a password `NEW_PASSWORD` refers to the password you need to set</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab2="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Unzip the downloaded file to get the executable file:</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">unzip</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist-xxxx.zip</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Run the program</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Obtain administrator information The following two different versions, the new version also has random generation and manual settings</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Versions lower than v3.25.0</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># higher than v3.25.0 version</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Randomly generate a password</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Manually set a password `NEW_PASSWORD` refers to the password you need to set</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">.</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">\</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab3="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Install</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">scoop</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Run</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> server</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</Tabs>
<h2 id="daemon" tabindex="-1"><a class="header-anchor" href="#daemon"><span><strong>Daemon</strong></span></a></h2>
<Tabs :data='[{"id":"linux"},{"id":"macOS"},{"id":"Windows"}]' tab-id="os">
<template #title0="{ value, isActive }">linux</template>
<template #title1="{ value, isActive }">macOS</template>
<template #title2="{ value, isActive }">Windows</template>
<template #tab0="{ value, isActive }">
<p><code v-pre>vim /usr/lib/systemd/system/alist.service</code> add the following content, where path_alist is the path where alist is located</p>
<div class="language-ini line-numbers-mode" data-highlighter="shiki" data-ext="ini" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-ini"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">[Unit]</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">Description</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">alist</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">After</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">network.target</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#98C379"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">[Service]</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">Type</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">simple</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">WorkingDirectory</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">path_alist</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">ExecStart</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">path_alist/alist server</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">Restart</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">on-failure</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#98C379"> </span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">[Install]</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#C678DD">WantedBy</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#383A42;--shiki-dark:#98C379">multi-user.target</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Then <code v-pre>systemctl daemon-reload</code>, now you can use these commands to manage the program:</p>
<ul>
<li>Start: <code v-pre>systemctl start alist</code></li>
<li>Shut down: <code v-pre>systemctl stop alist</code></li>
<li>Self-start: <code v-pre>systemctl enable alist</code></li>
<li>Cancel Self-start: <code v-pre>systemctl disable alist</code></li>
<li>Status: <code v-pre>systemctl status alist</code></li>
<li>Restart: <code v-pre>systemctl restart alist</code></li>
</ul>
<p>Daemon will not use? <a href="https://www.bilibili.com/video/BV1rF41197Qv?t=187.0" target="_blank" rel="noopener noreferrer"><strong>Video Tutorial</strong></a></p>
</template>
<template #tab1="{ value, isActive }">
<p>Edit <code v-pre>~/Library/LaunchAgents/ci.nn.alist.plist</code> in any way and add the following content, modify <code v-pre>path_alist</code> to be the path where AList is located, and <code v-pre>path/to/working/dir</code> to be the working path of AList</p>
<div class="language-xml line-numbers-mode" data-highlighter="shiki" data-ext="xml" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-xml"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;?</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">xml</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> version</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"1.0"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> encoding</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"UTF-8"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">?></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;!</span><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">DOCTYPE</span><span style="--shiki-light:#E45649;--shiki-dark:#E5C07B"> plist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">plist</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> version</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"1.0"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">dict</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>Label&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>ci.nn.alist&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>KeepAlive&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">true</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>ProcessType&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>Background&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>RunAtLoad&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">true</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">/></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>WorkingDirectory&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>path/to/working/dir&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>ProgramArguments&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">key</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">array</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">             &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>path_alist/alist&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">             &#x3C;</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">>server&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">string</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">         &#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">array</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">     &#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">dict</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;/</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">plist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Then, execute <code v-pre>launchctl load ~/Library/LaunchAgents/ci.nn.alist.plist</code> to load the configuration, now you can use these commands to manage the program:</p>
<ul>
<li>Start: <code v-pre>launchctl start ~/Library/LaunchAgents/ci.nn.alist.plist</code></li>
<li>Close: <code v-pre>launchctl stop ~/Library/LaunchAgents/ci.nn.alist.plist</code></li>
<li>Unload configuration: <code v-pre>launchctl unload ~/Library/LaunchAgents/ci.nn.alist.plist</code></li>
</ul>
</template>
<template #tab2="{ value, isActive }">
<h3 id="method-one" tabindex="-1"><a class="header-anchor" href="#method-one"><span><strong>method one</strong></span></a></h3>
<ol>
<li>Download the newest <code v-pre>nssm</code> from <a href="https://nssm.cc/download" target="_blank" rel="noopener noreferrer">https://nssm.cc/download</a>.</li>
<li>Unzip the archive and go to the diretory of <code v-pre>nssm.exe</code>.</li>
<li>Hold Shift and right click on the blank space, then release and press S or select &quot;powershell here&quot;, you should now see a blue window named &quot;Windows PowerShell&quot;.</li>
<li>Type <code v-pre>.\nssm.exe install alist</code>.</li>
<li>Select the path of <code v-pre>alist.exe</code> for &quot;Path&quot;, e.g. <code v-pre>D:\alist\alist.exe</code>; type <code v-pre>server</code> for &quot;Argument&quot;.</li>
<li>You can custom &quot;Display Name&quot;, &quot;Description&quot; and &quot;Startup Type&quot; in &quot;Details&quot; tab.</li>
<li>Go to &quot;I/O&quot; tab and select a file for both &quot;Output (stdout)&quot; and &quot;Output (stderr)&quot;, e.g. <code v-pre>D:\alist\stdout.log</code>. The file itself (<code v-pre>stdout.log</code>) may not exist, but the folder (<code v-pre>D:\alist</code>) must exist.</li>
<li>Click on &quot;Install Service&quot;.</li>
</ol>
<p>You can now start the service from services.msc or task manager.</p>
<h3 id="method-two" tabindex="-1"><a class="header-anchor" href="#method-two"><span><strong>method two</strong></span></a></h3>
<p>Use <strong><code v-pre>.VBS</code></strong> script to start and stop, create two scripts respectively start.vbs and stop.vbs</p>
<p>Just double-click to start it in the folder at the same level as the Alist startup program, don't worry about no response, just go to the browser to access it</p>
<div class="hint-container info">
<p class="hint-container-title">Two startup scripts</p>
<p><strong>start.vbs</strong></p>
<div class="code-block-with-title">
  <div class="code-block-title-bar" data-title="vbscript">
    <span>vbscript</span>
  </div>
  <div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Dim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ws</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ws</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> =</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Wscript.CreateObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"Wscript.Shell"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ws.run</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "alist.exe server",vbhide</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Wscript.quit</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div>
</div><p><strong>stop.vbs</strong></p>
<div class="code-block-with-title">
  <div class="code-block-title-bar" data-title="vbscript">
    <span>vbscript</span>
  </div>
  <div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Dim</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ws</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ws</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> =</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Wscript.CreateObject</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">"Wscript.Shell"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">ws.run</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "taskkill /f /im alist.exe",0</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">Wscript.quit</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div>
</div><ol>
<li>
<p>If the script will not be created, you can download it yourself: <a href="https://www.alipan.com/s/DHPMhRtKUzY/folder/63e0961eae317bd4d4d945cda69dbb00f9837fb7" target="_blank" rel="noopener noreferrer"><strong>Script Download</strong></a></p>
</li>
<li>
<p>If the script will not be used, you can watch the video: <a href="https://www.bilibili.com/video/BV1DG411s7j5?t=266.2" target="_blank" rel="noopener noreferrer"><strong>reference video</strong></a></p>
</li>
</ol>
<p>How to realize Windows startup automatically, you can refer to the script mentioned above to use the video (second).</p>
</div>
</template>
</Tabs>
<div class="hint-container info">
<p class="hint-container-title">Info</p>
<p>For all platform, you can use follow command to silent start, stop and restart. (v3.4.0 and later)</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># start server with `--force-bin-dir`</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> start</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># stop server by pid</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> stop</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># restart server by pid</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> restart</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div>
<h2 id="how-to-update" tabindex="-1"><a class="header-anchor" href="#how-to-update"><span><strong>How to update</strong></span></a></h2>
<p>Download the new version of Alist and replace the previous one.</p>
<ul>
<li>Status: <code v-pre>systemctl status alist</code></li>
<li>Restart: <code v-pre>systemctl restart alist</code></li>
</ul>
<h2 id="get-password" tabindex="-1"><a class="header-anchor" href="#get-password"><span><strong>Get Password</strong></span></a></h2>
<p>You need to enter the directory folder where the script installs AList and execute the following command</p>
<h4 id="lower-than-v3-25-0" tabindex="-1"><a class="header-anchor" href="#lower-than-v3-25-0"><span>Lower than v3.25.0</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="higher-than-v3-25-0" tabindex="-1"><a class="header-anchor" href="#higher-than-v3-25-0"><span>Higher than v3.25.0</span></a></h4>
<p>Versions above 3.25.0 change the password to an encrypted hash value, and the password cannot be calculated directly. If the password is forgotten, it can only be re-<strong><code v-pre>randomly generated</code></strong> or <strong><code v-pre>manually set</code></strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Randomly generate a password</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Manually set a password, `NEW_PASSWORD` refers to the password you need to set</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="what-should-i-do-if-it-keeps-loading" tabindex="-1"><a class="header-anchor" href="#what-should-i-do-if-it-keeps-loading"><span><strong>What should I do if it keeps loading?</strong></span></a></h2>
<p>I mounted some network disks but they cannot be used. I restarted AList and found that I could not enter. The web page prompts: <code v-pre>Failed to obtain settings: Please wait, storage is loading</code>. What should I do?</p>
<ol>
<li>Wait a few minutes</li>
<li>Stop the failed/unstartable storage by using the command</li>
</ol>
<Tabs :data='[{"id":"Linux"},{"id":"Windows"},{"id":"Mac"},{"id":"Docker"}]' tab-id="stop">
<template #title0="{ value, isActive }">Linux</template>
<template #title1="{ value, isActive }">Windows</template>
<template #title2="{ value, isActive }">Mac</template>
<template #title3="{ value, isActive }">Docker</template>
<template #tab0="{ value, isActive }">
<p>If you stop by command <mark>You must first enter the folder where your AList is located and enter the command</mark></p>
<p>If we don’t know which storage is causing the problem, we can list all storages through the command</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# ./alist storage list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌─────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│─────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     S3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                /R2</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                             true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     UrlTree</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">           /233</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                            true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└─────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>After entering the query command, we will enter another mode and cannot operate. If there are too many added storages, you can use the ↑ and ↓ keys on the keyboard to scroll down. After you find it, you can press <code v-pre>Ctrl+C</code> to exit.</p>
<p>For example, because the storage <code v-pre>233</code> cannot be loaded, we enter the command to stop it, and then restart AList.</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /233</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# ./alist storage disable /233</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> path</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [/233] have been disabled</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p></p>
</template>
<template #tab1="{ value, isActive }">
<p>If you stop by command <mark>You must first enter the folder where your AList is located and enter the command</mark></p>
<p>If we don’t know which storage is causing the problem, we can list all storages through the command</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">C:\Users\admin\Desktop\alist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">onfig.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 13</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌──────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│──────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     AliyundriveOpen</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   /open</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                           true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 9</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     Local</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">             /code</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                           true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 10</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    AList</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> V3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">          /ceshi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                          true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└──────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>After entering the query command, we will enter another mode and cannot operate. If there are too many added storages, you can use the ↑ and ↓ keys on the keyboard to scroll down. After you find it, you can press <code v-pre>Ctrl+C</code> to exit.</p>
<p>For example, because the storage <code v-pre>open</code> cannot be loaded, we enter the command to stop it, and then restart AList.</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /open</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">C:\Users\admin\Desktop\alist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /open</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">onfig.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> path</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [/open] have been disabled</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p></p>
</template>
<template #tab2="{ value, isActive }">
<p>If you stop by command <mark>You must first enter the folder where your AList is located and enter the command</mark></p>
<p>Since I don’t have a Mac device at the moment, I can’t provide specific examples, but the commands are the same and you can refer to Linux and Windows.</p>
<p>If we don’t know which storage is causing the problem, we can list all storages through the command</p>
<p>List storage:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>Stop storage:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /Path</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p></p>
</template>
<template #tab3="{ value, isActive }">
<p>The <code v-pre>Docker</code> here currently only provides the default version installed using the document command. <mark>If you build multiple Docker versions of AList, you need to modify individual parameters~</mark></p>
<p>If we don’t know which storage is causing the problem, we can list all storages through the command</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> exec</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -it</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# docker exec -it alist ./alist storage list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌─────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│─────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     PikPakShare</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /pikpak</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                         true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /utena_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /adelev_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 4</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /megan_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 5</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /patti_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└─────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>After entering the query command, we will enter another mode and cannot operate. If there are too many added storages, you can use the ↑ and ↓ keys on the keyboard to scroll down. After you find it, you can press <code v-pre>Ctrl+C</code> to exit.</p>
<p>For example, because the storage <code v-pre>pikpak</code> cannot be loaded, we enter the command to stop it, and then restart AList.</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> exec</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -it</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /pikpak</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">&#x3C;!</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">--</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"> #include-env-end --></span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div></div></div></template>
</Tabs>
</div></template>


