<template><div><p>Only for Linux-x86_64/arm64 platform.</p>
<Tabs :data='[{"id":"Latest"},{"id":"Beta"}]'>
<template #title0="{ value, isActive }">Latest</template>
<template #title1="{ value, isActive }">Beta</template>
<template #tab0="{ value, isActive }">
<p><strong>Install</strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/v3-en.sh"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -o</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v3-en.sh</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x26;&#x26; </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v3-en.sh</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><img src="/img/guide/v3-install-en.png" alt="v3-install" loading="lazy"></p>
<p><strong>alist-manager</strong></p>
<p>&quot;Use command: alist or alist-manager&quot;<br>
<img src="/img/guide/alist-manager-en.png" alt="alist-manager" loading="lazy"></p>
<p></p>
</template>
<template #tab1="{ value, isActive }">
<p><strong>Install</strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/beta.sh"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><strong>Update</strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/beta.sh"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> update</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p><strong>Uninstall</strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/beta.sh"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> uninstall</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div></template>
</Tabs>
<h3 id="custom-path" tabindex="-1"><a class="header-anchor" href="#custom-path"><span><strong>Custom path</strong></span></a></h3>
<p>The default installation is in <code v-pre>/opt/alist</code>. To customize the installation path, add the installation path as the second parameter, which must be an absolute path (if the path ends in alist, install directly to the given path, otherwise it will be installed in the given path alist Directory), such as installing to <code v-pre>/root</code>:</p>
<Tabs :data='[{"id":"Latest"},{"id":"Beta"}]'>
<template #title0="{ value, isActive }">Latest</template>
<template #title1="{ value, isActive }">Beta</template>
<template #tab0="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Install</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/v3-en.sh"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -o</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v3-en.sh</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x26;&#x26; </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v3-en.sh</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /root</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># update</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/v3-en.sh"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -o</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v3-en.sh</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x26;&#x26; </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v3-en.sh</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> update</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /root</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Uninstall</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/v3-en.sh"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -o</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v3-en.sh</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> &#x26;&#x26; </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> v3-en.sh</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> uninstall</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /root</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab1="{ value, isActive }">
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Install</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/beta.sh"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> install</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /root</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># update</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/beta.sh"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> update</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /root</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Uninstall</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">curl</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -fsSL</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://alist.nn.ci/beta.sh"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">bash</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> uninstall</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /root</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
</Tabs>
<ul>
<li>Start: <code v-pre>systemctl start alist</code></li>
<li>Shut down: <code v-pre>systemctl stop alist</code></li>
<li>Status: <code v-pre>systemctl status alist</code></li>
<li>Restart: <code v-pre>systemctl restart alist</code></li>
</ul>
<h2 id="get-password" tabindex="-1"><a class="header-anchor" href="#get-password"><span><strong>Get Password</strong></span></a></h2>
<p>You need to enter the directory folder where the script installs AList and execute the following command</p>
<h4 id="lower-than-v3-25-0" tabindex="-1"><a class="header-anchor" href="#lower-than-v3-25-0"><span>Lower than v3.25.0</span></a></h4>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><h4 id="higher-than-v3-25-0" tabindex="-1"><a class="header-anchor" href="#higher-than-v3-25-0"><span>Higher than v3.25.0</span></a></h4>
<p>Versions above 3.25.0 change the password to an encrypted hash value, and the password cannot be calculated directly. If the password is forgotten, it can only be re-<strong><code v-pre>randomly generated</code></strong> or <strong><code v-pre>manually set</code></strong></p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Randomly generate a password</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> random</span></span>
<span class="line"><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic"># Manually set a password, `NEW_PASSWORD` refers to the password you need to set</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> admin</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> set</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> NEW_PASSWORD</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="what-should-i-do-if-it-keeps-loading" tabindex="-1"><a class="header-anchor" href="#what-should-i-do-if-it-keeps-loading"><span><strong>What should I do if it keeps loading?</strong></span></a></h2>
<p>I mounted some network disks but they cannot be used. I restarted AList and found that I could not enter. The web page prompts: <code v-pre>Failed to obtain settings: Please wait, storage is loading</code>. What should I do?</p>
<ol>
<li>Wait a few minutes</li>
<li>Stop the failed/unstartable storage by using the command</li>
</ol>
<Tabs :data='[{"id":"Linux"},{"id":"Windows"},{"id":"Mac"},{"id":"Docker"},{"id":"Other"}]' tab-id="stop">
<template #title0="{ value, isActive }">Linux</template>
<template #title1="{ value, isActive }">Windows</template>
<template #title2="{ value, isActive }">Mac</template>
<template #title3="{ value, isActive }">Docker</template>
<template #title4="{ value, isActive }">Other</template>
<template #tab0="{ value, isActive }">
<p>If you stop by command <mark>You must first enter the folder where your AList is located and enter the command</mark></p>
<p>If we don’t know which storage is causing the problem, we can list all storages through the command</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# ./alist storage list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:10]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌─────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│─────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     S3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                /R2</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                             true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     UrlTree</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">           /233</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                            true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└─────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>After entering the query command, we will enter another mode and cannot operate. If there are too many added storages, you can use the ↑ and ↓ keys on the keyboard to scroll down. After you find it, you can press <code v-pre>Ctrl+C</code> to exit.</p>
<p>For example, because the storage <code v-pre>233</code> cannot be loaded, we enter the command to stop it, and then restart AList.</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /233</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# ./alist storage disable /233</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> path</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [/233] have been disabled</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p></p>
</template>
<template #tab1="{ value, isActive }">
<p>If you stop by command <mark>You must first enter the folder where your AList is located and enter the command</mark></p>
<p>If we don’t know which storage is causing the problem, we can list all storages through the command</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">C:\Users\admin\Desktop\alist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">onfig.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:36:23]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 13</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌──────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">  │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│──────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     AliyundriveOpen</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">   /open</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                           true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 9</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     Local</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">             /code</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                           true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 10</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    AList</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> V3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">          /ceshi</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                          true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└──────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>After entering the query command, we will enter another mode and cannot operate. If there are too many added storages, you can use the ↑ and ↓ keys on the keyboard to scroll down. After you find it, you can press <code v-pre>Ctrl+C</code> to exit.</p>
<p>For example, because the storage <code v-pre>open</code> cannot be loaded, we enter the command to stop it, and then restart AList.</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /open</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">C:\Users\admin\Desktop\alist</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">></span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">alist.exe</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /open</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\c</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">onfig.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 18:41:43]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> path</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [/open] have been disabled</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p></p>
</template>
<template #tab2="{ value, isActive }">
<p>If you stop by command <mark>You must first enter the folder where your AList is located and enter the command</mark></p>
<p>Since I don’t have a Mac device at the moment, I can’t provide specific examples, but the commands are the same and you can refer to Linux and Windows.</p>
<p>If we don’t know which storage is causing the problem, we can list all storages through the command</p>
<p>List storage:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>Stop storage:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /Path</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p></p>
</template>
<template #tab3="{ value, isActive }">
<p>The <code v-pre>Docker</code> here currently only provides the default version installed using the document command. <mark>If you build multiple Docker versions of AList, you need to modify individual parameters~</mark></p>
<p>If we don’t know which storage is causing the problem, we can list all storages through the command</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> exec</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -it</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# docker exec -it alist ./alist storage list</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 11:50:08]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Found</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 8</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storages</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">┌─────────────────────────────────────────────────────────────────┐</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ID</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    Driver</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">            Mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Path</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">                      Enabled</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│─────────────────────────────────────────────────────────────────│</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     PikPakShare</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /pikpak</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                         true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /utena_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /adelev_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 4</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /megan_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">│</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 5</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">     OnedriveAPP</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">       /patti_onedrive</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">                 true</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">    │</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">└─────────────────────────────────────────────────────────────────┘</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>After entering the query command, we will enter another mode and cannot operate. If there are too many added storages, you can use the ↑ and ↓ keys on the keyboard to scroll down. After you find it, you can press <code v-pre>Ctrl+C</code> to exit.</p>
<p>For example, because the storage <code v-pre>pikpak</code> cannot be loaded, we enter the command to stop it, and then restart AList.</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">docker</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> exec</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -it</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ./alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /pikpak</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">[root@OPSD-g8xXordx3B9f alist]# docker exec -it alist ./alist storage disable /pikpak</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> reading</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> file:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> data/config.json</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> load</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> config</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> from</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> env</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> prefix:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ALIST_</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> init</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> logrus...</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">INFO[2023-11-23</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 17:54:52]</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> Storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> with</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> mount</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> path</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> [/pikpak] have been disabled</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></template>
<template #tab4="{ value, isActive }">
<p>Basically they are the same commands, only the prefix files are different, and the commands remain the same.</p>
<p>List storage:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> list</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p>Stop storage:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">alist</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> storage</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> disable</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> /path</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div></div></div><p></p>
</template>
</Tabs>
</div></template>


