<template><div><h1 id="run-from-source" tabindex="-1"><a class="header-anchor" href="#run-from-source"><span>Run from source</span></a></h1>
<div class="hint-container caution">
<p class="hint-container-title">Caution</p>
<p>This step is only for users who need to modify the source code by themselves. If you don't understand, please skip it.</p>
</div>
<h3 id="environmental-preparation" tabindex="-1"><a class="header-anchor" href="#environmental-preparation"><span><strong>Environmental preparation</strong></span></a></h3>
<p>First, you need to have an environment of <code v-pre>git</code>, <code v-pre>nodejs</code>, <code v-pre>pnpm</code>, <code v-pre>golang&gt;=1.20</code>, <code v-pre>gcc</code></p>
<h3 id="building-the-front-end" tabindex="-1"><a class="header-anchor" href="#building-the-front-end"><span><strong>Building the front end</strong></span></a></h3>
<p>Use <code v-pre>git clone --recurse-submodules https://github.com/alist-org/alist-web.git</code> command to clone this project, execute <code v-pre>pnpm install &amp;&amp; pnpm build</code> to get the target file in the dist directory</p>
<h3 id="build-the-backend" tabindex="-1"><a class="header-anchor" href="#build-the-backend"><span><strong>Build the backend</strong></span></a></h3>
<p>Clone <a href="https://github.com/alist-org/alist" target="_blank" rel="noopener noreferrer">https://github.com/alist-org/alist</a> for this project, copy the <code v-pre>dist</code> directory of the previous step to the <code v-pre>public</code> directory under the project, and then:</p>
<div class="language-bash line-numbers-mode" data-highlighter="shiki" data-ext="bash" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-bash"><span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">appName</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"alist"</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">builtAt</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">date</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> +'%F %T %z')"</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">goVersion</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">go</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> version</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sed</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 's/go version //'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gitAuthor</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> show</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -s</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --format=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'format:%aN &#x3C;%ae>'</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> HEAD</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">gitCommit</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> log</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --pretty=format:</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"%h"</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">version</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">git</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> describe</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --long</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --tags</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --dirty</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> --always</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">webVersion</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">$(</span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">wget</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -qO-</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -t1</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -T2</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "https://api.github.com/repos/alist-org/alist-web/releases/latest"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">grep</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> "tag_name"</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">head</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -n</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">awk</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -F</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> ":"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> '{print $2}'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> | </span><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">sed</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> 's/\"//g;s/,//g;s/ //g'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">ldflags</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-w -s </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.BuiltAt=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$builtAt</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.GoVersion=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$goVersion</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.GitAuthor=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$gitAuthor</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.GitCommit=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$gitCommit</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.Version=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$version</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">-X 'github.com/alist-org/alist/v3/internal/conf.WebVersion=</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$webVersion</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">' </span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">\</span></span>
<span class="line"><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span></span>
<span class="line"><span style="--shiki-light:#4078F2;--shiki-dark:#61AFEF">go</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> build</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> -ldflags=</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#E45649;--shiki-dark:#E06C75">$ldflags</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">"</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379"> .</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><details class="hint-container details"><summary>compilation tutorial videos you may need</summary>
<p>Windows version: <strong><a href="https://www.bilibili.com/video/BV1Xr4y1z723" target="_blank" rel="noopener noreferrer">https://www.bilibili.com/video/BV1Xr4y1z723</a></strong> (Although it is V2 version, it is the same as V3 version..)</p>
<p>Linux version: <strong><a href="https://www.bilibili.com/video/BV1GW4y1s742" target="_blank" rel="noopener noreferrer">https://www.bilibili.com/video/BV1GW4y1s742</a></strong></p>
<p>Fanwai compiled documents: <strong><a href="https://www.yuque.com/anwenya/alist/glqlhu" target="_blank" rel="noopener noreferrer">https://www.yuque.com/anwenya/alist/glqlhu</a></strong></p>
</details>
</div></template>


