<template><div><h1 id="简介" tabindex="-1"><a class="header-anchor" href="#简介"><span>简介</span></a></h1>
<div class="hint-container warning">
<p class="hint-container-title">注意</p>
<p>新版本（V3 及更高版本）与 V2 不兼容，因此如果您从 V2 升级，我们建议您完全重新安装 Alist。</p>
</div>
<p><a href="https://github.com/Xhofe/alist/releases/latest" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/release/Xhofe/alist?style=flat-square" alt="" loading="lazy"></a><br>
<a href="https://github.com/Xhofe/alist/discussions" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/discussions/Xhofe/alist?color=%23ED8936&amp;style=flat-square" alt="GitHub Discussions" loading="lazy"></a><br>
<a href="https://github.com/Xhofe/alist/actions?query=workflow%3ABuild" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/actions/workflow/status/Xhofe/alist/build.yml?style=flat-square" alt="" loading="lazy"></a><br>
<a href="https://github.com/Xhofe/alist/releases" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/github/downloads/Xhofe/alist/total?style=flat-square&amp;color=%239F7AEA" alt="" loading="lazy"></a></p>
<!-- [![](https://img.shields.io/badge/%24-donate-ff69b4.svg?style=flat-square)](https://pay.xhofe.top) -->
<h2 id="what-s-this" tabindex="-1"><a class="header-anchor" href="#what-s-this"><span>What's this</span></a></h2>
<p>一个支持多种存储，支持网页浏览和 WebDAV 的文件列表程序，由 gin 和 Solidjs 驱动。</p>
<h2 id="support-storage" tabindex="-1"><a class="header-anchor" href="#support-storage"><span>Support storage</span></a></h2>
<ul class="task-list-container">
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-0" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-0"> <RouteLink to="/zh/guide/drivers/local.html">本机存储</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-1" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-1"> <RouteLink to="/zh/guide/drivers/Crypt.html">Crypt</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-2" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-2"> <RouteLink to="/zh/guide/drivers/aliyundrive_open.html">阿里云盘Open</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-3" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-3"> <a href="https://www.alipan.com/" target="_blank" rel="noopener noreferrer">阿里云盘</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-4" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-4"> <RouteLink to="/zh/guide/drivers/onedrive.html">OneDrive</RouteLink> /<RouteLink to="/zh/guide/drivers/onedrive_app.html">APP</RouteLink>/ SharePoint（<a href="https://www.office.com/" target="_blank" rel="noopener noreferrer">国际版</a>, <a href="https://portal.partner.microsoftonline.cn" target="_blank" rel="noopener noreferrer">世纪互联</a>,de,us）</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-5" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-5"> <a href="https://drive.google.com/" target="_blank" rel="noopener noreferrer">GoogleDrive</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-6" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-6"> <a href="https://www.123pan.com/" target="_blank" rel="noopener noreferrer">123云盘/分享/直链</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-7" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-7"> FTP / SFTP</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-8" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-8"> <a href="https://www.mypikpak.com/" target="_blank" rel="noopener noreferrer">PikPak / 分享</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-9" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-9"> <RouteLink to="/zh/guide/drivers/s3.html">S3[对象存储]</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-10" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-10"> <RouteLink to="/zh/guide/drivers/s3.html#%E6%B7%BB%E5%8A%A0%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8%E7%A4%BA%E4%BE%8B%E5%8F%8A%E5%AE%98%E6%96%B9%E6%96%87%E6%A1%A3">多吉云</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-11" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-11"> <a href="https://www.upyun.com/products/file-storage" target="_blank" rel="noopener noreferrer">又拍云对象存储</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-12" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-12"> WebDAV(支持无API的OneDrive/SharePoint)</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-13" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-13"> Teambition（<a href="https://www.teambition.com/" target="_blank" rel="noopener noreferrer">中国</a>，<a href="https://us.teambition.com/" target="_blank" rel="noopener noreferrer">国际</a>）</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-14" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-14"> <a href="https://www.mediatrack.cn/" target="_blank" rel="noopener noreferrer">分秒帧</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-15" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-15"> <a href="https://cloud.189.cn" target="_blank" rel="noopener noreferrer">天翼云盘</a> (个人云, 家庭云)</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-16" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-16"> <a href="https://yun.139.com/" target="_blank" rel="noopener noreferrer">中国移动云盘</a> (个人云, 家庭云)</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-17" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-17"> <a href="https://pan.wo.cn" target="_blank" rel="noopener noreferrer">中国联通云盘</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-18" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-18"> <a href="https://mopan.sc.189.cn/mopan/#/downloadPc" target="_blank" rel="noopener noreferrer">四川电信魔盘</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-19" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-19"> <a href="https://disk.yandex.com/" target="_blank" rel="noopener noreferrer">Yandex.Disk</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-20" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-20"> <a href="https://pan.baidu.com/" target="_blank" rel="noopener noreferrer">百度网盘</a> / <RouteLink to="/zh/guide/drivers/baidu_share.html">分享</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-21" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-21"> <a href="https://pan.quark.cn" target="_blank" rel="noopener noreferrer">夸克网盘/TV</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-22" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-22"> <RouteLink to="/zh/guide/drivers/thunder.html">迅雷网盘 / X / 浏览器</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-23" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-23"> <a href="https://www.lanzou.com/" target="_blank" rel="noopener noreferrer">蓝奏云</a>、<a href="https://www.ilanzou.com" target="_blank" rel="noopener noreferrer">蓝奏云优享版</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-24" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-24"> <a href="https://feijipan.com/" target="_blank" rel="noopener noreferrer">小飞机网盘</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-25" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-25"> <a href="https://www.alipan.com/" target="_blank" rel="noopener noreferrer">阿里云盘分享</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-26" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-26"> <a href="https://photos.google.com/" target="_blank" rel="noopener noreferrer">谷歌相册</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-27" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-27"> <a href="https://mega.nz" target="_blank" rel="noopener noreferrer">Mega.nz</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-28" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-28"> <a href="https://photo.baidu.com/" target="_blank" rel="noopener noreferrer">一刻相册</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-29" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-29"> <a href="https://www.terabox.com/" target="_blank" rel="noopener noreferrer">TeraBox -海外百度</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-30" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-30"> <RouteLink to="/zh/guide/drivers/Alist%20V2%20V3.html">AList v2/v3</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-31" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-31"> SMB</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-32" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-32"> <RouteLink to="/zh/guide/advanced/alias.html">别名</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-33" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-33"> <a href="https://115.com/" target="_blank" rel="noopener noreferrer">115</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-34" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-34"> <a href="https://www.seafile.com/" target="_blank" rel="noopener noreferrer">Seafile</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-35" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-35"> Cloudreve</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-36" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-36"> <a href="https://trainbit.com/" target="_blank" rel="noopener noreferrer">Trainbit</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-37" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-37"> <RouteLink to="/zh/guide/drivers/UrlTree.html">UrlTree</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-38" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-38"> IPFS</label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-39" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-39"> <a href="https://drive.uc.cn/" target="_blank" rel="noopener noreferrer">UC网盘/TV</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-40" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-40"> <a href="https://www.dropbox.com" target="_blank" rel="noopener noreferrer">Dropbox</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-41" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-41"> <a href="https://www.weiyun.com/" target="_blank" rel="noopener noreferrer">腾讯微云</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-42" disabled="disabled"><label class="task-list-item-label" for="task-item-42"> <a href="https://app.v.tencent.com/" target="_blank" rel="noopener noreferrer">腾讯智能创作平台</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-43" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-43"> <RouteLink to="/zh/guide/drivers/chaoxing.html">超星星小组盘</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-44" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-44"> <a href="https://quqi.com" target="_blank" rel="noopener noreferrer">曲奇云盘</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-45" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-45"> <RouteLink to="/zh/guide/drivers/163music.html">网易云音乐云盘</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-46" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-46"> <RouteLink to="/zh/guide/drivers/halalcloud.html">6盘</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-47" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-47"> <a href="https://pc.lenovo.com.cn" target="_blank" rel="noopener noreferrer">联想家庭储存链接分享</a></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-48" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-48"> <RouteLink to="/zh/guide/drivers/github.html">GitHub API</RouteLink> / <RouteLink to="/zh/guide/drivers/github_releases.html">GitHub Release</RouteLink></label></li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" id="task-item-49" checked="checked" disabled="disabled"><label class="task-list-item-label" for="task-item-49"> <a href="https://misskey-hub.net/cn/docs/for-users/features/drive/" target="_blank" rel="noopener noreferrer">Misskey</a></label></li>
</ul>
<h2 id="discussion" tabindex="-1"><a class="header-anchor" href="#discussion"><span>Discussion</span></a></h2>
<p>一般问题请到<a href="https://github.com/Xhofe/alist/discussions" target="_blank" rel="noopener noreferrer">讨论论坛</a> ，<strong>issue仅针对错误报告和功能请求。</strong></p>
<h2 id="演示" tabindex="-1"><a class="header-anchor" href="#演示"><span>演示</span></a></h2>
<ul>
<li><a href="https://al.nn.ci" target="_blank" rel="noopener noreferrer">https://al.nn.ci</a></li>
</ul>
<!-- ## 特别赞助

- [VidHub](https://zh.okaapps.com/product/1659622164?ref=alist) - 苹果生态下优雅的网盘视频播放器，iPhone，iPad，Mac，Apple TV全平台支持。
- [亚洲云](https://www.asiayun.com/aff/QQCOOQKZ) - 高防服务器|服务器租用|福州高防|广东电信|香港服务器|美国服务器|海外服务器 - 国内靠谱的企业级云计算服务提供商 (国内API服务器赞助)
- [找资源](http://zhaoziyuan2.cc/) - 阿里云盘资源搜索引擎 -->
<h2 id="许可" tabindex="-1"><a class="header-anchor" href="#许可"><span>许可</span></a></h2>
<p><code v-pre>AList</code> 是在 AGPL-3.0 许可下许可的开源软件。</p>
</div></template>


