<template><div><h1 id="_2fa" tabindex="-1"><a class="header-anchor" href="#_2fa"><span>2FA</span></a></h1>
<p>To enable 2-factor authentication, you need to install a app that support 2FA (such as <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank" rel="noopener noreferrer">Google Authenticator</a>,<a href="https://support.microsoft.com/en-us/account-billing/download-and-install-the-microsoft-authenticator-app-351498fc-850a-45da-b7b6-27e523b8702a" target="_blank" rel="noopener noreferrer">Microsoft Authenticator</a>), on your phone.</p>
<p>Then login to ALIST manage and goto <code v-pre>Profile</code> page, click <code v-pre>Enable 2FA</code> button, scan the QR code with your 2FA app, and enter the code generated by your 2FA app.</p>
<p>Finally, click <code v-pre>Verify</code> button to enable 2FA.</p>
<ul>
<li>Each user can set a different &quot;2FA&quot; verification, how to cancel see the method below</li>
</ul>
<br/>
<h2 id="how-to-cancel-2fa-verification" tabindex="-1"><a class="header-anchor" href="#how-to-cancel-2fa-verification"><span><strong>How to cancel 2FA verification:</strong></span></a></h2>
<p>one、(≥ v3.15.0)</p>
<blockquote>
<p>If you forget the 2FA of your non-Admin account, you can tell the administrator to clear it for you</p>
<p>Enter the background --&gt; user, click &quot;cancel two-step verification&quot;</p>
<p>If the 2FA of the admin account is lost, please see the second step how to clear 2FA</p>
</blockquote>
<p>two、</p>
<blockquote>
<p>How to enter the folder where Alist is located</p>
<ul>
<li>
<ol>
<li><strong>Windows</strong>: Go to the folder where Alist is located and enter: <strong>alist.exe cancel2fa</strong></li>
</ol>
</li>
<li>
<ol start="2">
<li><strong>Linux</strong>: Enter the folder where Alist is located and input, <strong>./alist cancel2fa</strong></li>
</ol>
</li>
<li>
<ol start="3">
<li><strong>docker</strong>: docker directly input <strong>docker exec -it alist ./alist cancel2fa</strong></li>
</ol>
</li>
</ul>
<p><strong>After the above input is deleted, it is found that there is still a restart~</strong></p>
</blockquote>
<p>three、(&gt;3.30.0)</p>
<blockquote>
<p>Open the manage user page, you can see the option of the <code v-pre>Cancel 2FA</code>. After the cancellation, if you still have 2FA, you can choose to restart the Alist</p>
<ul>
<li>You need to use the new version, if there is no option of the <code v-pre>Cancel 2Fa</code>，Explain that you need to update the version</li>
</ul>
</blockquote>
</div></template>


